server:
  port: 8080

services:
  query-understanding: http://query-understanding-service:7003/process
  nlp: http://nlp-embedding-service:7002/embed
  vector-search: http://vector-search-service:7001/search
  ltr: http://ltr-service:7005/rerank
  ab-assign: http://ab-testing-service:7004/assign
  ab-log: http://ab-testing-service:7004/log
